import {
  Achievement,
  AddLarge,
  AddSmall,
  Aim,
  AllDevices,
  Android,
  AndroidFill,
  Apple,
  AppleFill,
  Archive,
  Armchair,
  ArrowDown,
  ArrowForwardLeft,
  ArrowForwardRight,
  ArrowLeft,
  ArrowLeftDown,
  ArrowLeftUp,
  ArrowRight,
  ArrowRightDown,
  ArrowRightUp,
  ArrowUp,
  At,
  Atom,
  Attachment,
  Attention,
  AttentionColor,
  AttentionMonochrome,
  BackyardTree,
  Barrier,
  BatteryChargeEmpty,
  BatteryChargeHalf,
  BatteryEmpty,
  BatteryFill,
  Bed,
  Bluetooth,
  BoardText,
  Book,
  Breaking,
  Broom,
  Calculator,
  Calendar,
  Call,
  CallIncoming,
  CallNoComing,
  CallOutgoing,
  Camera,
  CameraCeiling,
  CameraGroup,
  CameraStreet,
  Car,
  CaretSort,
  CaretSortDown,
  CaretSortUp,
  Cart,
  CartOn,
  Chat,
  CheckLarge,
  Checklist,
  CheckSmall,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronSort,
  ChevronUp,
  CloseLarge,
  CloseSmall,
  Clothes,
  Cloud,
  CloudDownload,
  CloudUpload,
  CoffeeBreak,
  Comments,
  Console,
  Contacts,
  Controller,
  Copy,
  Counter,
  CoworkingSitting,
  Cross,
  DarkTheme,
  DarkThemeFill,
  DeliveryBox,
  DeliveryBus,
  DeliveryCourier,
  DeliveryEnvelope,
  Desktop,
  Disability,
  Dislike,
  DividerDot,
  DividerHorizontal,
  DividerVertical,
  Document,
  DocumentAdd,
  DocumentEdit,
  Dollar,
  Door,
  DoorExit,
  Download,
  Drop,
  DrWeb,
  Edit,
  Education,
  Equaliser,
  EqualiserClear,
  Equipment,
  Error,
  ErrorColor,
  ErrorMonochrome,
  Escalator,
  EscalatorDown,
  EscalatorUp,
  EsetNod,
  Euro,
  Facebook,
  FacebookFill,
  FaceFrouning,
  FaceFrouningColor,
  FaceGrin,
  FaceGrinColor,
  FaceNeutral,
  FaceNeutralColor,
  FaceOpenMouth,
  FaceOpenMouthColor,
  FaceRage,
  FaceRageColor,
  FaceSmiling,
  FaceSmilingColor,
  FastForward,
  FastForward10s,
  FastForward15s,
  FastForward30s,
  FastForward5s,
  FastRewind,
  FastRewind10s,
  FastRewind15s,
  FastRewind30s,
  FastRewind5s,
  Favorite,
  FavoriteFill,
  FigureMan,
  FigureManWoman,
  FigureWoman,
  Filter,
  FilterAdd,
  FilterClear,
  FilterFill,
  Fire,
  Flag,
  Flickr,
  FlickrFill,
  Focus3D,
  FocusAR,
  FocusRecords,
  FocusVR,
  Folder,
  FolderAdd,
  FolderDetails,
  FolderShared,
  Food,
  GalleryHorizontal,
  GalleryVertical,
  Game,
  Geolocation,
  GeolocationSmall,
  Github,
  GithubFill,
  Gitlab,
  GitlabFill,
  GooglePlay,
  GooglePlayFill,
  Googleplus,
  Group,
  HandBreak,
  Heart,
  HeartBroken,
  HeartFill,
  Help,
  HelpColor,
  HelpMonochrome,
  History,
  HistoryAction,
  Home,
  Image,
  Incognito,
  Information,
  InformationColor,
  InformationMonochrome,
  Instagram,
  InstagramFill,
  Intercom,
  Internet,
  Invoice,
  Kettlebell,
  KeyPassword,
  Kluch,
  KluchFill,
  Launch,
  Lego,
  Licey,
  LiceyFill,
  Lift,
  LightBulb,
  Like,
  Link,
  LinkNative,
  Live,
  Lock,
  Mail,
  MailInbox,
  MailIncoming,
  MailOutgoing,
  Mailru,
  Map,
  MarketingFunnel,
  Maximize,
  Melody,
  Menu,
  MenuBullets,
  MenuFuture,
  MenuFutureBullets,
  MenuFutureKebab,
  MenuKebab,
  Merge,
  Microchip,
  Microcircuit,
  Microphone,
  MicrophoneTalker,
  MicrosoftOffice,
  Minimize,
  Mobile,
  MobileRefresh,
  More,
  Motion,
  None,
  NoneColor,
  NoneMonochrome,
  Notification,
  NotificationNew,
  Odnoklassniki,
  OdnoklassnikiFill,
  OfficeChair,
  Ok,
  OkColor,
  OkMonochrome,
  Onlime,
  OnlimeFill,
  OperatorSupport,
  OtherService,
  Overview1Screen,
  Overview2Screen,
  Overview4Screen,
  Overview6Screen,
  ParentsControl,
  Pass,
  PasswordHide,
  PasswordShow,
  Pause,
  PaymentCard,
  PaymentCardToCard,
  Percentage,
  Phone,
  Photo,
  Pin,
  PinFill,
  Play,
  PlayNext,
  PlayPrevious,
  Portfolio,
  Present,
  Print,
  Profile,
  ProgressDownload,
  Promocode,
  Pulse,
  Puzzle,
  Rating,
  RatingFill,
  RatingHalf,
  Redo,
  Refresh,
  RefreshSmall,
  Registrator,
  RemoveSmall,
  Rename,
  Rostelecom,
  RostelecomFill,
  Rotate3D,
  Ruble,
  Sber,
  Screen4K,
  ScreenControl,
  ScreenHD,
  ScreenSubscription,
  ScreenTV,
  Search,
  Security,
  Send,
  Server,
  SetOfMinutes,
  Settings,
  SettingsAdjust,
  Share,
  Ship,
  ShoppingBasket,
  Shuffle,
  SignIn,
  SignOut,
  SIM,
  Skip,
  SkipColor,
  SkipMonochrome,
  SmartHome,
  SmartHomeFill,
  Socket,
  SortDown,
  SortUp,
  SOS,
  Speed1x,
  Speed2x,
  Speed4x,
  Speed6x,
  Speed8x,
  SpeedPlayback,
  Split,
  Stairs,
  StatisticsBoard,
  StatisticsCircular,
  StatisticsColumn,
  StatisticsCurve,
  StatisticsLine,
  Subtitles,
  SubtitlesFill,
  Synchronization,
  SynchronizationSmall,
  Tablet,
  TamTam,
  Target,
  Telegram,
  TelegramFill,
  TestSpeed,
  TheatreMasks,
  TheatreMasksFill,
  ThermalImager,
  Thermometer,
  TimeLarge,
  TimeSmall,
  Translation,
  Trash,
  Twitter,
  TwitterFill,
  Typography,
  Undo,
  Union,
  Unlimited,
  Unlock,
  Upload,
  User,
  UserMan,
  Users,
  UserTransgender,
  UserWoman,
  VacationBeach,
  VacationSea,
  Viber,
  VIP,
  Vkontakte,
  VkontakteFill,
  Voice,
  VolumeDown,
  VolumeOff,
  VolumeUp,
  VRHelmet,
  VRMask,
  Wallet,
  WhatsApp,
  WiFi,
  Windows,
  WindowsFill,
  Wink,
  WinkFill,
  Yandex,
  YandexDisk,
  YandexDiskFill,
  Youtube,
  YoutubeFill,
  ZoomIn,
  ZoomOut,
} from '@design-system-rt/rtk-ui-kit';
import CardComponents from '../CardComponent/CardComponents';
import React from 'react';

export const icons = [
  {
    name: 'Resizable',
    count: 87,
    collection: [
      <AddLarge />,
      <AddSmall />,
      <Attachment />,
      <Call />,
      <CallIncoming />,
      <CallNoComing />,
      <CallOutgoing />,
      <CaretSort />,
      <CaretSortUp />,
      <CaretSortDown />,
      <Chat />,
      <Copy />,
      <DarkTheme />,
      <DarkThemeFill />,
      <Dislike />,
      <Download />,
      <Edit />,
      <Equaliser />,
      <EqualiserClear />,
      <Favorite />,
      <FavoriteFill />,
      <Filter />,
      <FilterAdd />,
      <FilterClear />,
      <FilterFill />,
      <GalleryHorizontal />,
      <GalleryVertical />,
      <Group />,
      <Image />,
      <Like />,
      <Heart />,
      <HeartFill />,
      <Link />,
      <LinkNative />,
      <Live />,
      <Lock />,
      <Mail />,
      <MailInbox />,
      <MailIncoming />,
      <MailOutgoing />,
      <MarketingFunnel />,
      <Merge />,
      <Microphone />,
      <Notification />,
      <NotificationNew />,
      <PasswordHide />,
      <PasswordShow />,
      <Photo />,
      <Portfolio />,
      <Print />,
      <ProgressDownload />,
      <Rating />,
      <RatingFill />,
      <RatingHalf />,
      <Refresh />,
      <RefreshSmall />,
      <RemoveSmall />,
      <Rename />,
      <Send />,
      <SettingsAdjust />,
      <Share />,
      <Shuffle />,
      <SignIn />,
      <SignOut />,
      <SortDown />,
      <SortUp />,
      <SOS />,
      <Split />,
      <StatisticsCircular />,
      <StatisticsColumn />,
      <StatisticsCurve />,
      <StatisticsLine />,
      <Synchronization />,
      <SynchronizationSmall />,
      <TestSpeed />,
      <Translation />,
      <Trash />,
      <Union />,
      <Unlock />,
      <Upload />,
      <Voice />,
      <VolumeDown />,
      <VolumeOff />,
      <VolumeUp />,
    ],
  },
  {
    name: 'Entity',
    count: 137,
    collection: [
      <Aim />,
      <Atom />,
      <BackyardTree />,
      <Achievement />,
      <AllDevices />,
      <Archive />,
      <Armchair />,
      <BatteryChargeEmpty />,
      <BatteryChargeHalf />,
      <BatteryEmpty />,
      <BatteryFill />,
      <Bed />,
      <Barrier />,
      <Bluetooth />,
      <BoardText />,
      <Book />,
      <Breaking />,
      <Broom />,
      <Calculator />,
      <Calendar />,
      <Camera />,
      <CameraCeiling />,
      <CameraGroup />,
      <CameraStreet />,
      <Car />,
      <Cart />,
      <CartOn />,
      <Clothes />,
      <Cloud />,
      <CloudDownload />,
      <CloudUpload />,
      <CoffeeBreak />,
      <Comments />,
      <Console />,
      <Contacts />,
      <Controller />,
      <Counter />,
      <CoworkingSitting />,
      <Cross />,
      <DeliveryBox />,
      <DeliveryBus />,
      <DeliveryCourier />,
      <DeliveryEnvelope />,
      <Desktop />,
      <Disability />,
      <Document />,
      <DocumentAdd />,
      <DocumentEdit />,
      <Dollar />,
      <Door />,
      <DoorExit />,
      <Drop />,
      <Education />,
      <Equipment />,
      <Escalator />,
      <EscalatorDown />,
      <EscalatorUp />,
      <Euro />,
      <FigureMan />,
      <FigureManWoman />,
      <FigureWoman />,
      <Fire />,
      <Flag />,
      <Food />,
      <Game />,
      <HandBreak />,
      <HeartBroken />,
      <History />,
      <HistoryAction />,
      <Incognito />,
      <Intercom />,
      <Internet />,
      <Invoice />,
      <Kettlebell />,
      <KeyPassword />,
      <Launch />,
      <Lift />,
      <LightBulb />,
      <Melody />,
      <Microchip />,
      <Microcircuit />,
      <MicrophoneTalker />,
      <Mobile />,
      <MobileRefresh />,
      <Motion />,
      <OfficeChair />,
      <OperatorSupport />,
      <OtherService />,
      <ParentsControl />,
      <Pass />,
      <PaymentCard />,
      <PaymentCardToCard />,
      <Percentage />,
      <Phone />,
      <Present />,
      <Profile />,
      <Promocode />,
      <Pulse />,
      <Puzzle />,
      <Registrator />,
      <Rotate3D />,
      <Ruble />,
      <Screen4K />,
      <ScreenControl />,
      <ScreenHD />,
      <ScreenSubscription />,
      <Security />,
      <Server />,
      <SetOfMinutes />,
      <Ship />,
      <ShoppingBasket />,
      <SIM />,
      <Socket />,
      <Stairs />,
      <StatisticsBoard />,
      <Tablet />,
      <Target />,
      <TheatreMasks />,
      <TheatreMasksFill />,
      <ThermalImager />,
      <Thermometer />,
      <TimeLarge />,
      <TimeSmall />,
      <ScreenTV />,
      <Unlimited />,
      <User />,
      <UserMan />,
      <Users />,
      <UserTransgender />,
      <UserWoman />,
      <VacationBeach />,
      <VacationSea />,
      <VIP />,
      <VRHelmet />,
      <VRMask />,
      <Wallet />,
      <WiFi />,
    ],
  },
  {
    name: 'Info',
    count: 21,
    collection: [
      <Attention />,
      <AttentionColor />,
      <AttentionMonochrome />,
      <Error />,
      <ErrorColor />,
      <ErrorMonochrome />,
      <Help />,
      <HelpColor />,
      <HelpMonochrome />,
      <Information />,
      <InformationColor />,
      <InformationMonochrome />,
      <None />,
      <NoneColor />,
      <NoneMonochrome />,
      <Ok />,
      <OkColor />,
      <OkMonochrome />,
      <Skip />,
      <SkipColor />,
      <SkipMonochrome />,
    ],
  },
  {
    name: 'Navigation',
    count: 78,
    collection: [
      <ArrowDown />,
      <ArrowForwardLeft />,
      <ArrowForwardRight />,
      <ArrowLeft />,
      <ArrowLeftDown />,
      <ArrowRightUp />,
      <ArrowRight />,
      <ArrowRightDown />,
      <ArrowUp />,
      <ArrowLeftUp />,
      <CheckLarge />,
      <Checklist />,
      <CheckSmall />,
      <ChevronDown />,
      <ChevronLeft />,
      <ChevronRight />,
      <ChevronSort />,
      <ChevronUp />,
      <CloseLarge />,
      <CloseSmall />,
      <DividerDot />,
      <DividerHorizontal />,
      <DividerVertical />,
      <FastForward />,
      <FastForward5s />,
      <FastForward10s />,
      <FastForward15s />,
      <FastForward30s />,
      <FastRewind />,
      <FastRewind5s />,
      <FastRewind10s />,
      <FastRewind15s />,
      <FastRewind30s />,
      <Focus3D />,
      <FocusAR />,
      <FocusRecords />,
      <FocusVR />,
      <Folder />,
      <FolderAdd />,
      <FolderDetails />,
      <FolderShared />,
      <Geolocation />,
      <GeolocationSmall />,
      <Home />,
      <Map />,
      <Maximize />,
      <Menu />,
      <MenuBullets />,
      <MenuFuture />,
      <MenuFutureBullets />,
      <MenuFutureKebab />,
      <MenuKebab />,
      <Minimize />,
      <More />,
      <Overview1Screen />,
      <Overview2Screen />,
      <Overview4Screen />,
      <Overview6Screen />,
      <Pause />,
      <Pin />,
      <PinFill />,
      <Play />,
      <PlayNext />,
      <PlayPrevious />,
      <Redo />,
      <Search />,
      <Settings />,
      <Speed1x />,
      <Speed2x />,
      <Speed4x />,
      <Speed6x />,
      <Speed8x />,
      <SpeedPlayback />,
      <Subtitles />,
      <SubtitlesFill />,
      <Undo />,
      <ZoomIn />,
      <ZoomOut />,
    ],
  },
  {
    name: 'Smiles',
    count: 12,
    collection: [
      <FaceFrouning />,
      <FaceFrouningColor />,
      <FaceGrin />,
      <FaceGrinColor />,
      <FaceNeutral />,
      <FaceNeutralColor />,
      <FaceOpenMouth />,
      <FaceOpenMouthColor />,
      <FaceRage />,
      <FaceRageColor />,
      <FaceSmiling />,
      <FaceSmilingColor />,
    ],
  },
  {
    name: 'Social',
    count: 54,
    collection: [
      <Android />,
      <AndroidFill />,
      <Apple />,
      <AppleFill />,
      <At />,
      <DrWeb />,
      <EsetNod />,
      <Facebook />,
      <FacebookFill />,
      <Flickr />,
      <FlickrFill />,
      <Github />,
      <GithubFill />,
      <Gitlab />,
      <GitlabFill />,
      <GooglePlay />,
      <GooglePlayFill />,
      <Googleplus />,
      <Instagram />,
      <InstagramFill />,
      <Kluch />,
      <KluchFill />,
      <Lego />,
      <Licey />,
      <LiceyFill />,
      <Mailru />,
      <MicrosoftOffice />,
      <OdnoklassnikiFill />,
      ,
      <Odnoklassniki />,
      <Onlime />,
      <OnlimeFill />,
      <Rostelecom />,
      <RostelecomFill />,
      <Sber />,
      <SmartHome />,
      <SmartHomeFill />,
      <TamTam />,
      <Telegram />,
      <TelegramFill />,
      <Twitter />,
      <TwitterFill />,
      <Viber />,
      <Vkontakte />,
      <VkontakteFill />,
      <WhatsApp />,
      <Windows />,
      <WindowsFill />,
      <Wink />,
      <WinkFill />,
      <Yandex />,
      <YandexDisk />,
      <YandexDiskFill />,
      <Youtube />,
      <YoutubeFill />,
    ],
  },
];

export const elementsStyles = [
  {
    colors: ['primary1', 'primary2', 'secondary1', 'secondary2'],
    shapes: ['rounded', 'geometric', 'circular'],
    views: ['primary', 'outline', 'ghost'],
    sizes: ['small', 'medium', 'large'],
    sizesCatted: ['small', 'medium'],
    types: [
      'error',
      'info',
      'warning',
      'success',
      'primary1',
      'primary2',
      'secondary1',
      'secondary2',
    ],
  },
];

export const tabsStyles = [
  {
    colors: ['primary1', 'primary2', 'secondary1', 'secondary2'],
    sizes: ['small', 'medium', 'small', 'medium'],
    classicBar: [true, false, true, false],
    scrollable: [true, false, true, false],
  },
];

export const TextComponents = () => {
  return (
    <div className="text-category-blocks-container">
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="mega">Mega заголовок</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="h1">Заголовок первого уровня</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="h2">Заголовок второго уровня</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="h3">Заголовок третьего уровня</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="h4">Заголовок четвертого уровня</Typography>
        </CardComponents>
      </div>

      <br />

      <div className="components-category-block">
        <CardComponents>
          <Typography variant="bodyL">Основной текст 1</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="bodyM">Основной текст 2</Typography>
        </CardComponents>
      </div>

      <br />

      <div className="components-category-block">
        <CardComponents>
          <Typography variant="caption">Вспомогательный текст 1</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="description">Вспомогательный текст 2</Typography>
        </CardComponents>
      </div>

      <br />

      <div className="components-category-block">
        <CardComponents>
          <Typography variant="accentL">Акцентный текст 1</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="accentM">Акцентный текст 2</Typography>
        </CardComponents>
      </div>
      <div className="components-category-block">
        <CardComponents>
          <Typography variant="accentS">Акцентный текст 3</Typography>
        </CardComponents>
      </div>
    </div>
  );
};
